name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: npm run build:assets

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Validate HTML
        run: npm run validate:html || echo "HTML validation completed with warnings"

  build-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: npm run build:assets

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Optimize assets
        run: |
          # Optimize images (if any)
          find site -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.svg" | while read file; do
            echo "Optimizing $file"
            # Add image optimization commands here if needed
          done

      - name: Generate sitemap
        run: |
          echo "Generating sitemap..."
          # Add sitemap generation if needed

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          cname: # Add custom domain if needed
